// Cliente de Supabase configurado para esta aplicación.
// Lee las variables de entorno con la URL y la clave pública del proyecto Supabase,
// y crea el cliente tipado con soporte de base de datos.
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// URL del proyecto Supabase (definida en las variables de entorno)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;

// Clave pública (anon key) del proyecto Supabase
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Exporta el cliente de Supabase listo para usar en toda la aplicación.
// La sesión se guarda en localStorage y el token se refresca automáticamente.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,      // Persiste la sesión en el navegador
    persistSession: true,        // Mantiene la sesión entre recargas
    autoRefreshToken: true,      // Renueva el token de sesión automáticamente
  }
});
